
# Loads default set of integrations. Do not remove.
default_config:
homeassistant:
  allowlist_external_dirs:
    - /config/ev_logs

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-sidebar/custom-sidebar-yaml.js
#    - /config/www/community/lovelace-card-mod/card-mod.js
#    - /local/hass-fs-icons.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
utility_meter: !include /config/charger_helpers/utility_meters.yaml
input_text: !include /config/charger_helpers/input_text.yaml
input_number: !include /config/charger_helpers/input_number.yaml
template: !include /config/charger_helpers/template.yaml
sensor: !include /config/charger_helpers/sensor.yaml


# testing shell command
shell_command:
  get_pwd: '/config/dashboards/dir_check.sh 23'

# command_line attempt
command_line: !include command_line.yaml

lovelace:
  mode: yaml
  # load resources
  resources: !include /config/resources.yaml

  dashboards: !include dashboards/dashboards.yaml
  
python_script: